@echo off
setlocal enabledelayedexpansion
title ACHME CRM - Live Production Server

set "ROOT=%~dp0"
set "ROOT=%ROOT:~0,-1%"

:: ======================================================================
:: 1. ADMINISTRATOR ELEVATION
:: ======================================================================
net session >nul 2>&1
if %errorLevel% NEQ 0 (
    echo Requesting Administrator privileges...
    powershell -NoProfile -Command "Start-Process -FilePath '%ROOT%\start_live.bat' -Verb RunAs -WorkingDirectory '%ROOT%'"
    exit /b
)
echo [OK] Administrator privileges confirmed.
echo.
echo ====================================================================
echo  ACHME CRM - LIVE PRODUCTION DEPLOYMENT
echo ====================================================================
echo.

:: ======================================================================
:: 2. DETECT LAN IP
:: ======================================================================
echo [1/7] Detecting LAN IP...
set LAN_IP=
for /f "usebackq tokens=*" %%i in (`powershell -NoProfile -Command "$ip = (Find-NetRoute -RemoteIPAddress '8.8.8.8' -ErrorAction SilentlyContinue | Select-Object -First 1).LocalIPAddress; if (-not $ip) { $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' -and $_.InterfaceAlias -notmatch 'vEthernet|Loopback|Bluetooth' } | Select-Object -First 1).IPAddress }; $ip"`) do set LAN_IP=%%i
if "%LAN_IP%"=="" (
    for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /i "IPv4"') do (
        set "temp_ip=%%a"
        set "temp_ip=!temp_ip: =!"
        if "!temp_ip:~0,8!"=="192.168." set "LAN_IP=!temp_ip!"& goto :ip_found
        if "!temp_ip:~0,3!"=="10." set "LAN_IP=!temp_ip!"& goto :ip_found
        if "!temp_ip:~0,4!"=="172." set "LAN_IP=!temp_ip!"& goto :ip_found
    )
)
:ip_found
if "%LAN_IP%"=="" (
    echo [WARN] Could not detect LAN IP. Using 127.0.0.1
    set LAN_IP=127.0.0.1
) else (
    echo   LAN IP: %LAN_IP%
)

:: ======================================================================
:: 3. GENERATE backend\.env
:: ======================================================================
echo [2/7] Configuring backend .env with database credentials...
set "BE_ENV=%ROOT%\backend\.env"
(
echo # ============================================================
echo # ACHME CRM Backend - Production Configuration
echo # Auto-generated by start_live.bat
echo # ============================================================
echo.
echo # Server Configuration
echo PORT=82
echo NODE_ENV=production
echo ALLOWED_ORIGIN=http://%LAN_IP%:82,http://achme.com
echo DEFAULT_TEST_PASSWORD=Test@12345
echo.
echo # Database Configuration
echo DB_HOST=127.0.0.1
echo DB_PORT=3306
echo DB_USER=achme_user
echo DB_PASS=AchmeSecure@2024
echo DB_NAME=achme
echo.
echo # Email Configuration
echo SMTP_HOST=smtp.gmail.com
echo SMTP_PORT=587
echo EMAIL_USER=thanan757@gmail.com
echo EMAIL_PASS=ghjv omqm hwji kerq
echo.
echo # JWT Secret
echo JWT_SECRET=97418d0c15d57ade768586b8501e35d34e5a5277f2a0570b6d5b47ef93f5b33e88b80045c60efd77e6edcbb015dbe46cf6747ce1dd8f11361f3e426ddc677c9a
) > "%BE_ENV%"
if exist "%BE_ENV%" (echo   Done) else (echo [FAIL] & pause & exit /b)

:: ======================================================================
:: 4. GENERATE frontend\.env.production
:: ======================================================================
echo [3/7] Configuring frontend production build...
set "FE_ENV=%ROOT%\frontend\.env.production"
echo REACT_APP_API_URL= > "%FE_ENV%"
if exist "%FE_ENV%" (echo   Done) else (echo [FAIL] & pause & exit /b)

:: ======================================================================
:: 5. UPDATE WINDOWS HOSTS FILE (skip if already mapped or locked)
:: ======================================================================
echo [4/7] Mapping achme.com to %LAN_IP% in Windows hosts file...
set "HOSTS_FILE=C:\Windows\System32\drivers\etc\hosts"
findstr /i "achme" "%HOSTS_FILE%" >nul 2>&1
if %errorLevel%==0 (
    echo   Already mapped in hosts file
) else (
    powershell -NoProfile -Command "try { $h='%HOSTS_FILE%'; $c=Get-Content $h; $c+='%LAN_IP%    achme.com    www.achme.com'; Set-Content $h $c -Force; Write-Host 'ADDED' } catch { Write-Host 'LOCKED'; exit 1 }"
    if !errorLevel!==0 (echo   http://achme.com resolves to %LAN_IP%) else (echo   [WARN] Hosts file locked by another process)
)

:: ======================================================================
:: 6. BACKEND DEPENDENCIES + DATABASE
:: ======================================================================
echo [5/7] Setting up backend...
cd /d "%ROOT%\backend"
if not exist node_modules (
    echo   Installing backend packages...
    call npm install
    if !errorLevel! NEQ 0 (echo [FAIL] & pause & exit /b)
) else (
    echo   Backend packages already installed.
)
echo   Checking database connection...
call node db_init.js
if !errorLevel! NEQ 0 (
    echo [FAIL] Database check failed. Ensure MySQL is running.
    pause & exit /b
)

:: ======================================================================
:: 7. FRONTEND DEPENDENCIES + BUILD (skip if already built)
:: ======================================================================
echo [6/7] Setting up frontend...
cd /d "%ROOT%\frontend"
if not exist node_modules (
    echo   Installing frontend packages...
    call npm install
    if !errorLevel! NEQ 0 (echo [FAIL] & pause & exit /b)
) else (
    echo   Frontend packages already installed.
)
if exist "build\index.html" (
    echo   Build already exists (delete build\ folder to force rebuild)
) else (
    echo   Building React production bundle (this may take 1-2 minutes)...
    call npm run build
    if !errorLevel! NEQ 0 (echo [FAIL] & pause & exit /b)
    echo   Frontend build complete.
)

:: ======================================================================
:: 8. STOP OLD SERVER IF RUNNING, THEN START
:: ======================================================================
echo [7/7] Starting server on port 82...
cd /d "%ROOT%\backend"

:: Kill any existing node process on port 82
for /f "tokens=5" %%a in ('netstat -ano ^| findstr ":82 "') do (
    if "%%a" NEQ "" (
        taskkill /f /pid %%a >nul 2>&1
    )
)
timeout /t 2 /nobreak >nul

echo.
echo ====================================================================
echo  ACHME CRM IS NOW LIVE
echo ====================================================================
echo.
echo  Access from this PC:     http://localhost:82
echo  Access from LAN devices: http://%LAN_IP%:82
echo  Local domain:            http://achme.com
echo.
echo  Login: Kk@achmecommunication.com / kk@admin@123
echo.
echo  Press Ctrl+C to stop the server
echo ====================================================================
echo.

node server.js
pause
