@echo off
setlocal enabledelayedexpansion
title ACHME CRM - Live Production Server

set "ROOT=%~dp0"
set "ROOT=%ROOT:~0,-1%"
set "LIVE_PORT=82"
set "REDIRECT_PORT=80"

echo.
echo ====================================================================
echo  ACHME CRM - LIVE PRODUCTION STARTER
echo ====================================================================
echo.

call :elevate_if_needed
if "%ELEVATED_CHILD_STARTED%"=="1" exit /b 0
call :detect_ip
if errorlevel 1 exit /b 1
call :ensure_node
if errorlevel 1 exit /b 1
call :ensure_mysql
if errorlevel 1 exit /b 1
call :write_backend_env
if errorlevel 1 exit /b 1
call :write_frontend_env
if errorlevel 1 exit /b 1
call :map_hosts
if errorlevel 1 exit /b 1
call :install_backend
if errorlevel 1 exit /b 1
call :install_frontend_build
if errorlevel 1 exit /b 1
call :open_firewall_live
if errorlevel 1 exit /b 1
call :stop_port %LIVE_PORT%
if errorlevel 1 exit /b 1
call :stop_port %REDIRECT_PORT%
if errorlevel 1 exit /b 1

echo.
echo [FINAL] Starting ACHME CRM live server...
cd /d "%ROOT%\backend"

echo.
echo ====================================================================
echo  ACHME CRM IS LIVE
echo ====================================================================
echo.
echo  Open on this PC:       http://localhost:%LIVE_PORT%
echo  Open from LAN devices: http://%LAN_IP%:%LIVE_PORT%
echo  Local domain:          http://achme.com
echo.
echo  Health check:          http://%LAN_IP%:%LIVE_PORT%/api/health
echo  Login:                 Kk@achmecommunication.com / kk@admin@123
echo.
echo  Keep this window open. Press Ctrl+C to stop the live server.
echo ====================================================================
echo.

node server.js
pause
exit /b 0

:elevate_if_needed
echo [1/10] Checking Administrator access...
net session >nul 2>&1
if not errorlevel 1 (
  echo   Administrator access confirmed.
  exit /b 0
)
echo   Requesting Administrator access for hosts/firewall/port 80...
powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -FilePath '%ROOT%\start_live.bat' -Verb RunAs -WorkingDirectory '%ROOT%'"
set "ELEVATED_CHILD_STARTED=1"
exit /b 0

:detect_ip
echo [2/10] Detecting LAN IP...
set "LAN_IP="
for /f "usebackq tokens=*" %%i in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "$ip = (Find-NetRoute -RemoteIPAddress '8.8.8.8' -ErrorAction SilentlyContinue | Select-Object -First 1).LocalIPAddress; if (-not $ip) { $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' -and $_.InterfaceAlias -notmatch 'vEthernet|Loopback|Bluetooth' } | Select-Object -First 1).IPAddress }; $ip"`) do set "LAN_IP=%%i"
if "%LAN_IP%"=="" set "LAN_IP=127.0.0.1"
echo   LAN IP: %LAN_IP%
exit /b 0

:ensure_node
echo [3/10] Checking Node.js and npm...
where node >nul 2>&1
if errorlevel 1 (
  echo   Node.js was not found.
  where winget >nul 2>&1
  if errorlevel 1 (
    echo   [FAIL] Install Node.js 20 LTS from https://nodejs.org and run this file again.
    pause
    exit /b 1
  )
  echo   Installing Node.js LTS using winget...
  winget install -e --id OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements
  if errorlevel 1 goto fail
)
node --version
call npm --version
exit /b 0

:ensure_mysql
echo [4/10] Checking MySQL on port 3306...
powershell -NoProfile -ExecutionPolicy Bypass -Command "if (Get-NetTCPConnection -LocalPort 3306 -State Listen -ErrorAction SilentlyContinue) { exit 0 } else { exit 1 }"
if not errorlevel 1 (
  echo   MySQL is listening on port 3306.
  exit /b 0
)
echo   MySQL is not listening yet. Trying to start a local MySQL service...
for %%S in (MySQL80 MySQL MySQL57 mysql) do (
  net start %%S >nul 2>&1
  if not errorlevel 1 goto mysql_started
)
where winget >nul 2>&1
if errorlevel 1 (
  echo   [FAIL] MySQL is required. Install MySQL Server 8, create user achme_user, then run again.
  pause
  exit /b 1
)
echo   MySQL service was not found. Installing MySQL Server with winget...
winget install -e --id Oracle.MySQL --accept-package-agreements --accept-source-agreements
echo   After MySQL setup finishes, make sure the MySQL service is running and run this file again.
pause
exit /b 1
:mysql_started
echo   MySQL service started.
exit /b 0

:write_backend_env
echo [5/10] Writing backend production .env...
(
echo # ACHME CRM Backend - Production Configuration
echo # Auto-generated by start_live.bat
echo PORT=%LIVE_PORT%
echo NODE_ENV=production
echo ALLOWED_ORIGIN=http://localhost:%LIVE_PORT%,http://%LAN_IP%:%LIVE_PORT%,http://achme.com,http://www.achme.com
echo DEFAULT_TEST_PASSWORD=Test@12345
echo DB_HOST=127.0.0.1
echo DB_PORT=3306
echo DB_USER=achme_user
echo DB_PASS=AchmeSecure@2024
echo DB_NAME=achme
echo SMTP_HOST=smtp.gmail.com
echo SMTP_PORT=587
echo EMAIL_USER=thanan757@gmail.com
echo EMAIL_PASS=ghjv omqm hwji kerq
echo JWT_SECRET=97418d0c15d57ade768586b8501e35d34e5a5277f2a0570b6d5b47ef93f5b33e88b80045c60efd77e6edcbb015dbe46cf6747ce1dd8f11361f3e426ddc677c9a
) > "%ROOT%\backend\.env"
exit /b 0

:write_frontend_env
echo [6/10] Writing frontend production .env...
(
echo REACT_APP_API_URL=
echo REACT_APP_API_PROXY=
) > "%ROOT%\frontend\.env.production"
exit /b 0

:map_hosts
echo [7/10] Mapping achme.com to %LAN_IP% on this PC...
powershell -NoProfile -ExecutionPolicy Bypass -Command "$hosts = Join-Path $env:SystemRoot 'System32\drivers\etc\hosts'; $line = '%LAN_IP%    achme.com    www.achme.com'; $content = Get-Content $hosts -ErrorAction Stop; $filtered = $content | Where-Object { $_ -notmatch '\bachme\.com\b' }; $filtered + $line | Set-Content $hosts -Force -ErrorAction Stop"
if errorlevel 1 (
  echo   [WARN] Could not update hosts file. Run this file as Administrator or use http://%LAN_IP%:%LIVE_PORT%.
) else (
  echo   achme.com now points to %LAN_IP% on this PC.
)
exit /b 0

:install_backend
echo [8/10] Installing/checking backend dependencies...
cd /d "%ROOT%\backend"
call npm install
if errorlevel 1 goto fail
echo   Installing/checking Puppeteer browser...
call npx puppeteer browsers install chrome
if errorlevel 1 echo   [WARN] Puppeteer browser install failed. PDFs may fail until Chrome is installed.
echo   Ensuring ACHME database user exists...
call node ensure_db_user.js
if errorlevel 1 (
  echo.
  echo [FAIL] Database user setup failed.
  pause
  exit /b 1
)
echo   Checking database and creating tables if needed...
call node db_init.js
if errorlevel 1 (
  echo.
  echo [FAIL] Database login failed.
  echo        Ensure MySQL has user: achme_user
  echo        Password: AchmeSecure@2024
  echo        Database: achme
  pause
  exit /b 1
)
exit /b 0

:install_frontend_build
echo [9/10] Installing frontend dependencies and building production files...
cd /d "%ROOT%\frontend"
call npm install
if errorlevel 1 goto fail
call npm run build
if errorlevel 1 goto fail
exit /b 0

:open_firewall_live
echo [10/10] Opening Windows Firewall ports...
net session >nul 2>&1
if errorlevel 1 (
  echo   Not running as Administrator. If LAN devices cannot connect, allow TCP %LIVE_PORT% and %REDIRECT_PORT% in Windows Firewall.
  exit /b 0
)
netsh advfirewall firewall add rule name="ACHME CRM Live %LIVE_PORT%" dir=in action=allow protocol=TCP localport=%LIVE_PORT% >nul 2>&1
netsh advfirewall firewall add rule name="ACHME CRM Redirect %REDIRECT_PORT%" dir=in action=allow protocol=TCP localport=%REDIRECT_PORT% >nul 2>&1
echo   Firewall rules are ready.
exit /b 0

:stop_port
set "PORT_TO_STOP=%~1"
for /f "tokens=5" %%P in ('netstat -ano ^| findstr /r /c:":%PORT_TO_STOP% .*LISTENING"') do (
  taskkill /f /pid %%P >nul 2>&1
)
exit /b 0

:fail
echo.
echo [FAIL] Live setup failed. Check the error above, then run this file again.
pause
exit /b 1
